### ISSUE TITLE
Tor wall issue

### ISSUE THREAD

**Issue by Ekultek** [NullArray/NetSet#1]
![issue1](https://user-images.githubusercontent.com/14183473/59933177-88f94000-940e-11e9-8bb8-001435a3998f.png)
![issue2](https://user-images.githubusercontent.com/14183473/59933184-8b5b9a00-940e-11e9-9f84-6a65e40c25d0.png)

**Comment by NullArray** [comment]
If you `which iptables` what does it say? In any case i'll put the proper command there for anyone that has iptables not in `/sbin`

**Comment by NullArray** [comment]
That should take care of that.

https://github.com/NullArray/NetSet/commit/d665cce995f05c852e66a7291c75efd2d6ef8068

**Comment by NullArray** [comment]
> If you `which iptables` what does it say? In any case i'll put the proper command there for anyone that has iptables not in `/sbin`

Oh one more thing, it used to be that when written like so:

`nm=$(nmap -sS -Pn -T4 RHOST -O --reason)`

It wouldn't give any output until called  with `$nm`, i was operating under the assumption that that was still the case.
